version: "3.9"

services:
  database:
    image: ${DATABASE_IMAGE_TAG}
    container_name: database
    build:
      context: database
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${APP_IMAGE_TAG}
    platform: linux/amd64
    build:
      context: app
    ports:
      - 3000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - app_data:/app/dist/public
    
  nginx:
    image: ${NGINX_IMAGE_TAG}
    build:
      context: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: always
    volumes:
      - app_data:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  mongodb_data:
  app_data:
